version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
